version: '3.6'
services:   
  db:
      environment:
         MYSQL_ROOT_PASSWORD: root
         LANG: C.UTF-8
      command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      volumes:
          - ./init:/docker-entrypoint-initdb.d
          - ./dbdata:/var/lib/mysql
      container_name: mysqldb
      image: mysql
      restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
